[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

[cmd_duration]
disabled = true

[directory]
style = "bold blue"
truncation_length = 8
truncation_symbol = "…/"
read_only = " "

[container]
format = '[\[$name\]]($style) '

[aws]
symbol = "  "

[buf]
symbol = " "
format = "[$symbol]($style)"

[c]
symbol = " "

[cmake]
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "
format = "[$symbol]($style)"

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = "[$symbol]($style)"

[elm]
symbol = " "
format = "[$symbol]($style)"

[git_branch]
symbol = " "

[golang]
symbol = " "
format = "[$symbol]($style)"

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "
format = "[$symbol]($style)"

[hg_branch]
symbol = " "

[java]
symbol = " "
format = "[$symbol]($style)"

[julia]
symbol = " "
format = "[$symbol]($style)"

[lua]
symbol = " "
format = "[$symbol]($style)"

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "
format = "[$symbol]($style)"

[nim]
symbol = " "
format = "[$symbol]($style)"

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "[$symbol]($style)"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
#symbol = " "
symbol = ""

[perl]
format = "[$symbol]($style)"

[php]
format = "[$symbol]($style)"

[python]
symbol = " "
format = "[$symbol(\\(${virtualenv}\\))]($style)"

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "
format = "[$symbol]($style)"

[rust]
symbol = " "
format = "[$symbol]($style)"

[scala]
symbol = " "

[spack]
symbol = "🅢 "
